# -------- ArxivDigest configuration --------
topic: "Quantitative Finance"

# Run-time knobs 
lookback_days: 7            # how many recent days to pull from arXiv
category_filter_enabled: true   # false ⇒ ignore the “categories” list
threshold: 5                # min GPT relevance score to keep a paper

# Sub-topics to include (natural-language names as shown on arXiv)
categories:
  - "Portfolio Management"               # q-fin.PM  – mid/long-horizon trading & allocation
  - "Statistical Finance"                # q-fin.ST  – factor modelling, risk, forecasting
  - "Trading and Market Microstructure"  # q-fin.TR  – high-frequency order-book work

# Natural-language guidance for the LLM’s relevance judgement
interest: |
  1. **Interest hierarchy (highest → lowest)**  
       • Mid-frequency trading & allocation (holding periods ≈ hours-to-days, execution latency moderate)  
       • High-frequency / intraday microstructure (seconds-to-minutes, order-book signals, execution-cost modelling)  
       • Low-frequency or long-horizon asset-allocation & macro factor studies (monthly or longer horizons)
  2. Across all horizons, favour work that:
       • Presents back-tested or live results (Sharpe, information ratio, turnover, realistic transaction-costs)  
       • Provides clear methodology or code that can be reproduced  
       • Includes robustness checks or out-of-sample validation
  3. **Exclude** purely theoretical option-pricing papers with no trading or portfolio implications, language-specific NLP applications, and survey-only expository pieces.
