name: Crypto digest
on:
  schedule:
    # 09:15 CST every Wednesday  (01:15 UTC Wed)
    - cron: '15 1 * * 3'
  workflow_dispatch: {}

jobs:
  generate_digest:
    runs-on: ubuntu-latest
    permissions: { actions: write, contents: read }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: { python-version: 3.8 }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crypto digest
        run: python src/action.py --config config_crypto.yaml
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: crypto_digest.html
          path: crypto_digest.html